global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'payment-router-api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'

  - job_name: 'payment-router-listeners'
    static_configs:
      - targets: ['listeners:3001']

  - job_name: 'payment-router-router'
    static_configs:
      - targets: ['router:3002']

  - job_name: 'payment-router-settlement'
    static_configs:
      - targets: ['settlement:3003']

