[project]
name = "payment-router-contracts"
clarinet_version = "3.11.0"

[contracts.token-usdh-v2]
path = "token-usdh.clar"
clarity_version = 4
epoch = "3.3"

[contracts.agent-registry-v2]
path = "agent-registry.clar"
clarity_version = 4
epoch = "3.3"

[contracts.yield-vault-v2]
path = "yield-vault.clar"
depends_on = ["token-usdh-v2"]
clarity_version = 4
epoch = "3.3"

[contracts.payment-router-v2]
path = "payment-router.clar"
depends_on = ["agent-registry-v2", "yield-vault-v2"]
clarity_version = 4
epoch = "3.3"

[networks]
[networks.devnet]
node_rpc_address = "http://localhost:3999"
node_rpc_port = 3999
deployment_fee_rate = 1000

[networks.testnet]
node_rpc_address = "https://api.testnet.hiro.so"
node_rpc_port = 443
deployment_fee_rate = 1

[networks.mainnet]
node_rpc_address = "https://api.hiro.so"
node_rpc_port = 443
deployment_fee_rate = 1000

[requirements]
clarinet = ">=1.0.0"
